// <auto-generated />
namespace BankOfBIT_ZD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Assignment4_before_test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Assignment4_before_test));
        
        string IMigrationMetadata.Id
        {
            get { return "202210210308276_Assignment4_before_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
