// <auto-generated />
namespace BankOfBIT_ZD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class autogenerate_next_number : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(autogenerate_next_number));
        
        string IMigrationMetadata.Id
        {
            get { return "202210210558051_autogenerate_next_number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
